### ISSUE TITLE
Adding a container to a profile removes it from current profile

### ISSUE THREAD

**Issue by grkvlt** [Metaswitch/calico-docker#117] opened 2015-05-07 14:41 UTC
Is this expected behaviour? If I have multiple profiles, and I want containers A,B,C to be in profile X and C,D,E to be in profile Y, what happens is that container C is only in profile Y, it gets removed from X, but I really wanted it to be in both X and Y.

**Comment by tomdee** [comment] 2015-05-07 16:15
I suspect this is a bug. Are you using calicoctl or modifying etcd directly? If using calicoctl can you tell us the release you're using and the exact command line you used?

**Comment by robbrockbank** [comment] 2015-05-07 20:58
This is actually expected behaviour.  Only a single profile can be associated with a given endpoint.  Since each profile can contain a set of complicated rules, it is not trivial to algorithmically chain sets of rules together coming from different profiles - although this is something we are currently thinking about.

To do the behavior you're after, add tags for the profiles A and B, define a third profile C (which will be the union of profiles A and B) and add rules allowing traffic from the tags used in the profiles A and B.  Have a look at the following for more details on the data structures:
 
http://docs.projectcalico.org/en/latest/etcd-data-model.html

Closing the issue for now, but please re-open if you need additional information.

**Comment by lxpollitt** [comment] 2015-05-07 22:33
@robbrockbank - Actually we've just agreed to pull forward support for multiple profiles.  The data model will (shortly) support an ordered list of profiles associated with an endpoint (rather than just the single profile supported today).  Tags from the profiles will get combined into a single set.  The rules from the profiles will be appended to each other in the same order as the profiles are listed.  If none of the rules get hit for a particular packet then it will be dropped.  Otherwise the first rule that matches will be the one that is actioned.

Some folks will choose to use list of profiles in this way; others will be able to just use a single profile with smart use of tags.  But we will be giving orchestrators the flexibility so they can choose either, or mix and match as they want.

**Comment by grkvlt** [comment] 2015-05-09 16:33
@robbrockbank @lxpollitt OK that makes sense - for the moment i'll continue using a single profile, then. i haven't done much with creating tags automatically, but that ws going to be my next improvement with the Clocker integration. Keep me posted on any changes to the way profiles work though, please

**Comment by tomdee** [comment] 2015-05-14 17:36
Multiple profile support will be in the felix 0.21 release (in just over a week). We will do a calico-docker release shortly after.

**Comment by robbrockbank** [comment] 2015-05-22 00:05
The latest calico-docker release includes an updated felix with profile support.  However, this function is only accessible by directly writing to etcd.

Reopening issue to cover updating the calicoctl commands to allow multiple profiles to be configured.

**Comment by tomdee** [comment] 2015-06-15 21:46
@robbrockbank remember to reference/close this when you make the next release.

**Comment by robbrockbank** [comment] 2015-06-24 22:40
Closing out this issue, as there is a solution provided in the 0.4.6 release.

https://github.com/Metaswitch/calico-docker/releases/tag/v0.4.6

The old "profile member add" has been retired, and new "endpoint  <ENDPOINT ID> profile append|remove|set <LIST OF PROFILE NAMES>" command has been added.

You can use the command "container <CONTAINER ID> endpoint-id show" to determine the endpoint ID for a specific container.

**Closed by robbrockbank** 2015-06-24 22:40 UTC
