### ISSUE TITLE
Segfault in busybox container

### ISSUE THREAD

**Issue by spikecurtis** [Metaswitch/calico-docker#4] opened 2015-01-30 01:07 UTC
When I run the demo and attach to a container, then try to check its IP config, I get a segfault.

```
core@core-02 ~ $ docker attach $A

/ #
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
Segmentation fault (core dumped)
/ # exit
core@core-02 ~ $
```

Diags at:
https://transfer.sh/2iyBO/diags-20150130-010421.tar.gz

**Comment by Lukasa** [comment] 2015-01-30 11:03
Interesting. I don't have a working docker environment atm so I can't reproduce this, so I'll let @plwhite take a swing.

**Comment by plwhite** [comment] 2015-01-31 22:45
Not me, I'm afraid. I've never got this demo to work at all.

I'm going to guess Tom is the right person to assign it to.

**Comment by ed-harrison** [comment] 2015-02-02 13:01
FWIW - I can reproduce it quite readily using the demo in this repo.  I guess the question is whether it is something specific about the busybox containers in this demo (i.e. they'd segfault even if Docker were setting up the networking rather than Calico), or something in what Calico is doing (or not doing).

@plwhite do you have any of your containers from the work you've done on Metaswitch/calico-docker-prototype?  If so, could you see whether these hit the same issue when running ip addr?

**Comment by plwhite** [comment] 2015-02-02 13:16
Sorry, I misread this as an issue in the vagrant VMs. Cannot repro this here.

    root@calico-vm05:/home/ubuntu# docker attach 192_168_1_1
    root@bb19d26423a0:/#
    root@bb19d26423a0:/#
    root@bb19d26423a0:/# ip route
    default dev eth0  scope link
    root@bb19d26423a0:/# ip addr
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
        inet 127.0.0.1/8 scope host lo
           valid_lft forever preferred_lft forever
        inet6 ::1/128 scope host
           valid_lft forever preferred_lft forever
    110: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP    group default qlen 1000
        link/ether b2:90:83:31:f7:aa brd ff:ff:ff:ff:ff:ff
        inet 192.168.1.1/32 scope global eth0
           valid_lft forever preferred_lft forever
        inet6 fe80::b090:83ff:fe31:f7aa/64 scope link
           valid_lft forever preferred_lft forever

The code that sets up the IP configuration is different between the two demos though (though it should be issuing the same underlying commands); could well be a bug there. However, if `ip addr` is failing, then it sounds like something pretty fundamental must be broken.

The next two angles I would follow are : 

* Do the endpoints have connectivity? I rather assume not from this.
* Is there anything fishy under either the `/proc` filesystem or `/var/net`? I wonder about a bad symbolic link, for example (one of the ones set up in the original demo).

**Comment by ed-harrison** [comment] 2015-02-02 13:21
To answer your first question, yes the containers have connectivity.  In other words, the "demo" is working fine (i.e. from container $A I can ping container $D in the same security group but not container $B in a different one); it's just that this particular command fails.

I'm firing up my VMs again to check the latter question - do you want me to look on the host VM or in the container itself?

**Comment by tomdee** [comment] 2015-02-11 21:32
This is a bug in busybox. I suggest raising a bug there.

**Closed** 2015-03-05 19:34 UTC
